App:
  Port: 3001
  Domain: localhost
  JWTSecret: secretkey1995
  AllowedOrigins:
    - http://localhost/
  EnableCSRF: false
  EnableSubscriptions: false
  EnableAuth: false

DB:
  User: eirevpn_dev
  Password: eirevpn_dev
  Database: eirevpn_dev
  Host: localhost
  Port: 5432

Stripe:
  SecretKey: sk_test_sssssssssss
  EndpointSecret: whsec_ssssssssss
  IntegrationActive: false
  SuccessUrl: https://eirevpn.ie/success
  ErrorUrl: https://eirevpn.ie/error
