App:
  Port: 3001
  Domain: 0.0.0.0
  AllowedOrigins:
    - http://localhost:8080
DB:
  User: test
  Password: test
  Database: eirevpn_dev
  Host: localhost
  Port: 5432
Stripe:
  SecretKey: sk_test_kLGFCqgqvp8m4xItjb7tCutQ00aVWpUjWt
  EndpointSecret: whsec_NiHocSXUplUAkCIk2R4uai3gMXHYILPs
  IntegrationActive: true
  SuccessUrl: https://eirevpn.ie/success
  ErrorUrl: https://eirevpn.ie/error
